=== nikhil-imcs/xmljsonassignment/src/main/resources/xml/customer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.nikhil.com/customer" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.nikhil.com/customer">

    <complexType name="Customer">
    	<sequence>
    		<element name="customerId" type="string"></element>
    		<element name="custName" type="string"></element>
    		<element name="dob" type="date"></element>
    		<element name="address" type="tns:Address"></element>
    		<element name="paymentMethod" type="tns:PaymentMethod" minOccurs="1" maxOccurs="2"></element>
    		<element name="annualSalary" type="float"></element>
    	</sequence>
    </complexType>
    
    <complexType name="Address">
    	<sequence>
    		<element name="street" type="string"></element>
    		<element name="aptNo" type="string"></element>
    		<element name="city" type="string"></element>
    		<element name="state" type="string"></element>
    		<element name="zipcode" type="string"></element>
    	</sequence>
    </complexType>
    

    <complexType name="PaymentMethod">
    	<sequence>
    		<element name="cardNumber" type="string"></element>
    		<element name="cardName" type="string"></element>
    		<element name="dateFrom" type="date"></element>
    		<element name="dateExp" type="date"></element>
    		<element name="cardType">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="CREDITCARD"></enumeration>
    					<enumeration value="DEBITCARD"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    	</sequence>
    </complexType>


    <element name="Customer" type="tns:Customer"></element>
</schema>

=== nikhil-imcs/xmljsonassignment/src/main/resources/xml/custInfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Customer xmlns:tns="http://www.nikhil.com/customer" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.nikhil.com/customer customer.xsd ">
  <tns:customerId>100</tns:customerId>
  <tns:custName>Nikhil</tns:custName>
  <tns:dob>1993-06-06</tns:dob>
  <tns:address>
    <tns:street>6445 Love Dr</tns:street>
    <tns:aptNo>1036</tns:aptNo>
    <tns:city>Irving</tns:city>
    <tns:state>TX</tns:state>
    <tns:zipcode>75059</tns:zipcode>
  </tns:address>
  <tns:paymentMethod>
    <tns:cardNumber>4000826997638</tns:cardNumber>
    <tns:cardName>VISA</tns:cardName>
    <tns:dateFrom>2001-01-01</tns:dateFrom>
    <tns:dateExp>2020-01-01</tns:dateExp>
    <tns:cardType>CREDITCARD</tns:cardType>
  </tns:paymentMethod>
  <tns:annualSalary>60000.0</tns:annualSalary>
</tns:Customer>
